-- step 1: cross-region inference (ACCOUNTADMIN)
-- required for accounts outside AWS US regions
-- without this, AI_COMPLETE will return a model availability error

USE ROLE ACCOUNTADMIN;

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';

-- verify:
SHOW PARAMETERS LIKE 'CORTEX_ENABLED_CROSS_REGION' IN ACCOUNT;
-- value column should read AWS_US


-- step 2: role
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS CORTEXADMIN;
GRANT ROLE CORTEXADMIN TO ROLE ACCOUNTADMIN;

-- cortex code in snowsight
GRANT DATABASE ROLE SNOWFLAKE.COPILOT_USER TO ROLE CORTEXADMIN;

-- cortex AI functions (AI_COMPLETE, AI_PARSE_DOCUMENT, etc.)
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CORTEXADMIN;


-- step 3: warehouse
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS CORTEX_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;


-- step 4: database and schema
CREATE DATABASE IF NOT EXISTS CORTEX_DB;
CREATE SCHEMA IF NOT EXISTS CORTEX_DB.QUIZ_APP;


-- step 5: grants

-- warehouse
GRANT USAGE ON WAREHOUSE CORTEX_WH TO ROLE CORTEXADMIN;
GRANT OPERATE ON WAREHOUSE CORTEX_WH TO ROLE CORTEXADMIN;

-- database and schema
GRANT USAGE ON DATABASE CORTEX_DB TO ROLE CORTEXADMIN;
GRANT USAGE ON SCHEMA CORTEX_DB.QUIZ_APP TO ROLE CORTEXADMIN;

-- object creation in the schema
GRANT CREATE TABLE ON SCHEMA CORTEX_DB.QUIZ_APP TO ROLE CORTEXADMIN;
GRANT CREATE STAGE ON SCHEMA CORTEX_DB.QUIZ_APP TO ROLE CORTEXADMIN;
GRANT CREATE FILE FORMAT ON SCHEMA CORTEX_DB.QUIZ_APP TO ROLE CORTEXADMIN;
GRANT CREATE STREAMLIT ON SCHEMA CORTEX_DB.QUIZ_APP TO ROLE CORTEXADMIN;

-- future tables and stages
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA CORTEX_DB.QUIZ_APP TO ROLE CORTEXADMIN;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA CORTEX_DB.QUIZ_APP TO ROLE CORTEXADMIN;


-- step 6: verify
USE ROLE CORTEXADMIN;

USE WAREHOUSE CORTEX_WH;
USE DATABASE CORTEX_DB;
USE SCHEMA QUIZ_APP;

SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();